# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK Client. Web interaction practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'
  
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'


  # Pods for VK Client. Web interaction practice

end
